#!/usr/bin/env sh

alias yayinf='fzf-yay.sh -S'
alias cat='bat'

alias gitmain='git config user.email sn.sineto@gmail.com && git config core.sshCommand "ssh -i ~/.ssh/id_rsa_sineto"'
alias gitseco='git config user.email sinetoami@gmail.com && git config core.sshCommand "ssh -i ~/.ssh/id_rsa_sinetoami"'
alias gitdev='git config user.email sineto.dev@gmail.com && git config core.sshCommand "ssh -i ~/.ssh/id_rsa_sinetodev"'
alias gitmobiplus='git config user.email sinesio.neto@mobiplus.com.br && git config core.sshCommand "ssh -i ~/.ssh/id_rsa_mobiplus"'
alias snio_gitlab='git config user.email gitlab@snio.dev && git config core.sshCommand "ssh -i ~/.ssh/id_rsa_sniogitlab"'