#!/usr/bin/env sh

## PACKAGE MANAGER - YAY, PACMAN
alias yayinf='fzf-yay.sh -S'
alias yayrem='yay -Rscn'
alias yaycc='yay -Scc'

## PERSONAL GIT
alias gitmain='git config user.email sn.sineto@gmail.com && git config core.sshCommand "ssh -i ~/.ssh/id_rsa_sineto"'
alias gitseco='git config user.email sinetoami@gmail.com && git config core.sshCommand "ssh -i ~/.ssh/id_rsa_sinetoami"'
alias gitsndev='git config user.email sineto.dev@gmail.com && git config core.sshCommand "ssh -i ~/.ssh/id_rsa_sinetodev"'
alias gitmplus='git config user.email sinesio.neto@mobiplus.com.br && git config core.sshCommand "ssh -i ~/.ssh/id_rsa_mobiplus"'
alias git_snio_gitlab='git config user.email gitlab@snio.dev && git config core.sshCommand "ssh -i ~/.ssh/id_rsa_sniogitlab"'

## MISC
alias cat='bat'
alias listfonts='fc-list'
